# Generated by Django 5.1.7 on 2025-05-02 06:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_produce', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Mattuga', 'Mattuga'), ('Maganjo', 'Maganjo')], default='Mattuga', max_length=100)),
                ('type_of_produce', models.CharField(max_length=50)),
                ('date_of_arrival', models.DateField(auto_now_add=True)),
                ('time_of_arrival', models.TimeField(auto_now_add=True)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_dealer', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact', models.CharField(max_length=20)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('director', 'Director'), ('sales_agent', 'Sales Agent')], default='manager', max_length=20)),
                ('branch', models.CharField(blank=True, choices=[('Mattuga', 'Mattuga'), ('Maganjo', 'Maganjo')], max_length=100, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyers_name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Mattuga', 'Mattuga'), ('Maganjo', 'Maganjo')], default='Mattuga', max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('produce_name', models.CharField(max_length=100)),
                ('produce_type', models.CharField(max_length=50)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_date', models.DateField(auto_now_add=True)),
                ('sales_agent', models.ForeignKey(limit_choices_to={'role': 'sales_agent'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_produce', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Mattuga', 'Mattuga'), ('Maganjo', 'Maganjo')], default='Mattuga', max_length=100)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyers_name', models.CharField(max_length=100)),
                ('date_of_sale', models.DateField(auto_now_add=True)),
                ('time_of_sale', models.TimeField(auto_now_add=True)),
                ('sales_agent', models.ForeignKey(limit_choices_to={'role': 'sales_agent'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
